---
heroku:
  example-application-one:
    user: youruser
    password: yourpassword
  example-application-two:
    user: youruser
    password: yourpassword
s3:
  key: yourkey
  secret: yoursecret
  bucket: yourbucket
error_email: your@email.com